language: python
python:
  - "3.7"

dist: xenial

services:
  - docker

addons:
  apt:
    - gir1.2-gtk-3.0
    - python3-gi
    - python3-gi-cairo
    - python3-apt

env:
  - TESTFOLDER="pep8 small"
  - TESTFOLDER="medium"
script: PATH="/usr/bin:$PATH" ./runtests $TESTFOLDER
