language: python
python:
  - "3.4"
virtualenv:
  system_site_packages: true

dist: trusty

services:
  - docker

addons:
  apt:
    packages:
      - gir1.2-gtk-3.0
      - python3-gi
      - python3-gi-cairo
      - libapt-pkg-dev

install:
  - curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py && python3 /tmp/get-pip.py --user
  - pip3 install --user -r requirements.txt

env:
  - TESTFOLDER="pep8 small"
  - TESTFOLDER="medium"
script: ./runtests $TESTFOLDER
